
version: "3.9"
services:
  api-dev:
    # Use Debian-based image so we can install python and build tools for node-gyp
    image: node:20-bullseye
    container_name: tech-inventory-api-dev
    working_dir: /app
    command: sh -lc "apt-get update && apt-get install -y --no-install-recommends python3 build-essential && rm -rf /var/lib/apt/lists/*; npm ci --no-audit --no-fund || npm install --no-audit --no-fund; npm run dev"
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # prevent host node_modules from overlaying the container install (Windows -> Linux issues)
      - /app/node_modules
      - data-volume:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 20s
      timeout: 3s
      retries: 3

volumes:
  data-volume:
    driver: local
