
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-inventory-api:latest
    container_name: tech-inventory-api
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - data-volume:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 20s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  data-volume:
    driver: local
