name: PactFlow Demo

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  consumer:
    name: Consumer → generate & publish pacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Create .env for pact/verification scripts
        env:
          S_PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          V_PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN:      ${{ secrets.PACT_BROKER_TOKEN }}
          SH_OWNER:               ${{ vars.SH_OWNER }}
          SH_API:                 ${{ vars.SH_API }}
          SH_API_KEY:             ${{ secrets.SH_API_KEY }}
          SH_BASE_URL:            ${{ vars.SH_BASE_URL }}
          SH_RESOLVED:            ${{ vars.SH_RESOLVED }}
          SH_FLATTEN:             ${{ vars.SH_FLATTEN }}
          DEBUG_FETCH:            ${{ vars.DEBUG_FETCH }}
          PROVIDER_NAME:          ${{ vars.PROVIDER_NAME }}
          PROVIDER_BASE_URL:      ${{ vars.PROVIDER_BASE_URL }}
          PACT_OUT_DIR:           ${{ vars.PACT_OUT_DIR }}
          VERIFIER_LOG_TO_FILE:   ${{ vars.VERIFIER_LOG_TO_FILE }}
          PACT_LOG_LEVEL:         ${{ vars.PACT_LOG_LEVEL }}
          PUBLISH_VERIFICATION_RESULT: ${{ vars.PUBLISH_VERIFICATION_RESULT }}
          PACT_ENABLE_PENDING:    ${{ vars.PACT_ENABLE_PENDING }}
          PACT
